### ISSUE TITLE
Initializing the SRTC crashes the board

### ISSUE THREAD

**Issue by therealbstern** [imxrt-rs/imxrt-hal#150]
This is on a Teensy 4.0 using `teensy4-rs`.

When I initialize the SRTC, the code stops running.

A minimal example is at https://github.com/therealbstern/srtc-error

This worked with `teensy4-rs` 0.3 and `imxrt-ral` 0.4 but doesn't work with `teensy4-rs` 0.4 and `imxrt-ral` 0.5.

**Comment by mciantyre** [comment]
This issue doesn't reproduce using the `hal_srtc` example in this project, so it looks like the issue is in the BSP. Could you give mciantyre/teensy4-rs#154 a try? I think this patch directive in a Cargo.toml file should work:

```toml
[patch.crates-io.teensy4-bsp]
git = "https://github.com/mciantyre/teensy4-rs"
branch = "snvs-hp-cg"

```
